const {test}=require('node:test');const assert=require('node:assert/strict');const {setup,inline,tick}=require('./helpers.cjs');
const checkout='<input id="gep-coupon-code"><button id="gep-apply-coupon">Apply</button><div id="gep-coupon-status"></div><span id="gep-final-amount">100</span><button id="gep-pay-button">Pay</button>';
const config={GEP_Checkout:{ajaxurl:'/ajax',user_id:7,item_id:2,item_type:'test'}};
const payment={razorpay_order_id:'order_test',razorpay_payment_id:'pay_test',razorpay_signature:'test_signature'};
test('checkout reload recovers the same payment and keeps successful verification locked',async t=>{
 const p=await setup(checkout,'public/js/gep-checkout.js',config,w=>w.sessionStorage.setItem('gep_payment_7_test_2',JSON.stringify(payment)));t.after(p.close);
 assert.equal(p.$('#gep-pay-button').text(),'Retry payment verification');p.$('#gep-pay-button').trigger('click');assert.equal(p.requests[0].options.data.action,'gep_verify_payment');assert.equal(p.requests[0].options.data.razorpay_payment_id,'pay_test');
 p.requests[0].resolve({success:true,data:{redirect_url:'https://portal.example/dashboard/'}});assert.equal(p.w.sessionStorage.getItem('gep_payment_7_test_2'),null);assert.equal(p.$('#gep-pay-button').prop('disabled'),true);
});
test('payment recovery is scoped to the signed-in account',async t=>{
 const p=await setup(checkout,'public/js/gep-checkout.js',config,w=>w.sessionStorage.setItem('gep_payment_99_test_2',JSON.stringify(payment)));t.after(p.close);p.$('#gep-pay-button').trigger('click');assert.equal(p.requests[0].options.data.action,'gep_create_payment_order');
});
test('blocked payment storage and malformed order responses recover without script errors',async t=>{
 const p=await setup(checkout,'public/js/gep-checkout.js',config,w=>Object.defineProperty(w,'sessionStorage',{get(){throw new Error('denied');}}));t.after(p.close);p.$('#gep-pay-button').trigger('click');p.requests[0].resolve({success:true});assert.equal(p.$('#gep-pay-button').prop('disabled'),false);assert.match(p.$('#gep-payment-error').text(),/incomplete/);assert.deepEqual(p.errors,[]);
});
test('invalid coupon totals never render a negative charge',async t=>{
 const p=await setup(checkout,'public/js/gep-checkout.js',config);t.after(p.close);p.$('#gep-coupon-code').val('BAD');p.$('#gep-apply-coupon').trigger('click');p.requests[0].resolve({success:true,data:{new_total:-10,discount:110}});assert.equal(p.$('#gep-final-amount').text(),'100.00');assert.match(p.$('#gep-coupon-status').text(),/could not/);
});
test('support rejects whitespace, prevents duplicate sends and retains the message on failure',async t=>{
 const p=await setup('<form id="gep-support-form"><input id="support_subject"><textarea id="support_message"></textarea><button type="submit">Send</button><p id="support-status"></p></form>',inline('templates/dashboard/support.php','gep-support-form'));t.after(p.close);
 p.$('#support_subject').val(' ');p.$('#support_message').val('Help');p.$('form').trigger('submit');assert.equal(p.requests.length,0);p.$('#support_subject').val('Access');p.$('form').trigger('submit').trigger('submit');assert.equal(p.requests.length,1);p.requests[0].reject();assert.equal(p.$('#support_message').val(),'Help');assert.equal(p.$('button').prop('disabled'),false);assert.deepEqual(p.errors,[]);
});
test('course filters announce an empty result and restore all courses',async t=>{
 const p=await setup('<div id="gep-course-filters"><button class="filter-btn" data-filter="all">All</button><button class="filter-btn" data-filter="2">Math</button></div><div class="gep-premium-grid"><div class="gep-card-elite" data-category-id="1">Sanskrit</div></div>',inline('templates/dashboard/supercoaching.php','const filters'));t.after(p.close);
 p.$('[data-filter="2"]').trigger('click');assert.match(p.$('[role="status"]').text(),/No courses/);assert.equal(p.$('[data-filter="2"]').attr('aria-pressed'),'true');p.$('[data-filter="all"]').trigger('click');assert.equal(p.$('.gep-card-elite')[0].style.display,'flex');assert.match(p.$('[role="status"]').text(),/1 courses/);
});
test('policy deep links and browser history keep the selected content consistent',async t=>{
 const p=await setup(['terms','privacy','refund'].map(x=>`<a class="gep-policy-nav-link" data-tab="${x}">${x}</a><section class="gep-policy-section" id="tab-${x}"></section>`).join(''),inline('templates/dashboard/policies.php','switchTab'),{},w=>w.history.replaceState(null,'','#privacy'));t.after(p.close);
 assert.equal(p.$('#tab-privacy').hasClass('active'),true);p.w.document.querySelector('[data-tab="refund"]').click();assert.equal(p.w.location.hash,'#refund');p.w.history.replaceState(null,'','#terms');p.w.dispatchEvent(new p.w.PopStateEvent('popstate'));assert.equal(p.$('#tab-terms').hasClass('active'),true);assert.deepEqual(p.errors,[]);
});
test('PYQ year deep link selects the right panel; failed launch can retry',async t=>{
 const markup=['section_wise','year_wise'].map(x=>`<button class="gep-pyq-tab-btn" data-tab="${x}">${x}</button><div id="gep-pyq-tab-${x}" class="gep-pyq-tab-content"></div>`).join('')+'<button class="gep-pyq-practice-btn" data-type="year" data-target="2025">Practice</button>';
 const p=await setup(markup,inline('templates/dashboard/pyqs.php','Tab Swapping').replace(/<\?php[\s\S]*?\?>/g,'/ajax'),{},w=>w.history.replaceState(null,'','?tab=year_wise'));t.after(p.close);assert.equal(p.$('#gep-pyq-tab-year_wise')[0].style.display,'block');p.$('.gep-pyq-practice-btn').trigger('click').trigger('click');assert.equal(p.requests.length,1);p.requests[0].reject();assert.equal(p.$('.gep-pyq-practice-btn').prop('disabled'),false);assert.deepEqual(p.errors,[]);
});
test('doubt requests escape content, prevent duplicates and retain drafts on errors',async t=>{
 const p=await setup('<button class="t-btn" data-tab="disc">Discussion</button><div class="tab-pane" id="tab-disc"></div><div id="gep-doubt-list"></div><textarea id="gep-doubt-text"></textarea><button id="gep-submit-doubt" data-lesson-id="1" data-course-id="2">Post Doubt</button>',inline('templates/dashboard/watch.php','Tab Switching'));t.after(p.close);
 p.$('.t-btn').trigger('click');p.requests[0].resolve({success:true,data:[{question:'<img src=x>',answer:'<script>bad</script>'}]});assert.equal(p.$('#gep-doubt-list img, #gep-doubt-list script').length,0);assert.match(p.$('#gep-doubt-list').text(),/<img/);
 p.$('#gep-doubt-text').val('Please explain');p.$('#gep-submit-doubt').trigger('click').trigger('click');assert.equal(p.requests.length,2);p.requests[1].reject();assert.equal(p.$('#gep-doubt-text').val(),'Please explain');assert.equal(p.$('#gep-submit-doubt').prop('disabled'),false);assert.deepEqual(p.errors,[]);
});
const examMarkup='<div id="gep-exam-main-container"><div id="gep-timer"></div><div class="gep-question-block" data-id="1" data-cat-id="0"><div class="gep-options-container" data-qtype="numerical"><input class="gep-numerical-ans" value="42"></div></div><button class="gep-palette-btn" data-id="1" data-index="0"></button><button class="gep-calc-btn">Calculator</button><button id="gep-btn-instructions">Instructions</button></div><div id="gep-calculator-modal" style="display:none"><div><h3>Calculator</h3><button id="gep-calc-close">Close</button><input id="gep-calc-display">'+['2','+','=','1','/','0'].map(k=>`<button class="gep-calc-key" data-key="${k}">${k}</button>`).join('')+'<button id="gep-calc-apply">Use result as my answer</button></div></div><div id="gep-instructions-modal" style="display:none"><div><h2>Instructions</h2><button id="gep-inst-close">Close</button><a href="#rules">Rules</a></div></div>';
async function exam(){const fetches=[];const p=await setup(examMarkup,'public/js/gep-exam.js',{GEP_Exam:{remaining_seconds:600,elapsed_seconds:0,saved_answers:{},sections_data:[],attempt_id:1,ajaxurl:'/ajax'}},w=>{w.fetch=(url,o)=>{fetches.push(Object.fromEntries(o.body.entries()));return Promise.resolve({ok:true,json:async()=>({success:true})});};});p.fetches=fetches;return p;}
test('calculator requires explicit transfer and returns focus after Escape',async t=>{
 const p=await exam();t.after(p.close);p.w.document.querySelector('.gep-calc-btn').focus();p.$('.gep-calc-btn').trigger('click');await tick();assert.equal(p.w.document.activeElement.id,'gep-calc-close');for(const key of ['2','+','2','='])p.$(`[data-key="${key}"]`).trigger('click');assert.equal(p.$('#gep-calc-display').val(),'4');assert.equal(p.$('.gep-numerical-ans').val(),'42');assert.equal(p.fetches.length,0);
 p.$('#gep-calc-apply').trigger('click');await tick();assert.equal(p.$('.gep-numerical-ans').val(),'4');assert.equal(p.fetches[0].answer,'4');assert.equal(p.w.document.activeElement.className,'gep-calc-btn');assert.deepEqual(p.errors,[]);
});
test('calculator refuses division by zero and instructions trap and restore keyboard focus',async t=>{
 const p=await exam();t.after(p.close);p.$('.gep-calc-btn').trigger('click');await tick();for(const key of ['1','/','0','='])p.$(`[data-key="${key}"]`).trigger('click');assert.equal(p.$('#gep-calc-display').val(),'Error');p.$('#gep-calc-apply').trigger('click');assert.equal(p.fetches.length,0);
 p.w.document.getElementById('gep-calc-close').dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await tick();p.w.document.getElementById('gep-btn-instructions').focus();p.$('#gep-btn-instructions').trigger('click');await tick();assert.equal(p.$('#gep-instructions-modal [role="dialog"]').attr('aria-modal'),'true');
 const close=p.w.document.getElementById('gep-inst-close');close.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));assert.equal(p.w.document.activeElement.textContent,'Rules');p.w.document.activeElement.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await tick();assert.equal(p.w.document.activeElement.id,'gep-btn-instructions');assert.deepEqual(p.errors,[]);
});
test('analytics keeps readable results when the chart library is unavailable',async t=>{
 const p=await setup('<canvas id="gep-score-gauge"></canvas>','public/js/gep-analytics.js',{GEP_Analytics_Data:{percentage:50}});t.after(p.close);assert.match(p.$('body').text(),/Chart unavailable/);assert.equal(p.$('canvas').length,0);assert.deepEqual(p.errors,[]);
});
test('negative exam scores do not create negative chart arcs and reduced motion is respected',async t=>{
 const charts=[];const p=await setup('<canvas id="gep-score-gauge"></canvas>','public/js/gep-analytics.js',{GEP_Analytics_Data:{percentage:-20},Chart:function(el,config){charts.push(config);}},w=>w.matchMedia=()=>({matches:true}));t.after(p.close);assert.deepEqual(Array.from(charts[0].data.datasets[0].data),[0,100]);assert.equal(charts[0].options.animation.duration,0);assert.equal(p.$('canvas').attr('role'),'img');assert.deepEqual(p.errors,[]);
});
test('typing finish submits once and a late failure cannot overwrite the next session',async t=>{
 const markup='<div id="gep-typing-setup"><select id="gep-typing-paragraph"><option value="para1">Text</option></select><input name="gep_typing_dur" type="radio" value="60" checked><button id="gep-start-typing-btn">Start</button></div><div id="gep-typing-active"><div id="gep-typing-text-wrapper"></div><textarea id="gep-typing-input"></textarea><button id="gep-submit-early">Finish</button></div><div id="gep-typing-completed"><button id="gep-restart-test">Retry</button><p id="gep-typing-save-status"></p></div>';
 const p=await setup(markup,inline('templates/dashboard/typing-test.php','const paragraphs').replace(/<\?php[\s\S]*?\?>/g,'test-nonce'));t.after(p.close);p.$('#gep-start-typing-btn').trigger('click');p.$('#gep-submit-early').trigger('click').trigger('click');assert.equal(p.requests.length,1);p.$('#gep-restart-test').trigger('click');p.requests[0].reject();assert.equal(p.$('#gep-typing-save-status').text(),'');assert.equal(p.$('#gep-typing-input').prop('disabled'),false);assert.deepEqual(p.errors,[]);
});
test('series detail dialog names its content and closes with Escape',async t=>{
 const p=await setup('<button class="gep-view-details-btn" data-title="Sanskrit mock">Details</button><div id="gep-details-modal" style="display:none"><div role="dialog" aria-modal="true" aria-labelledby="gep-modal-title"><h2 id="gep-modal-title"></h2><button id="gep-details-modal-close">Close</button><img id="gep-modal-thumb"></div></div>',inline('templates/exam/series-view.php','detailsOpener'));t.after(p.close);p.w.document.querySelector('.gep-view-details-btn').focus();p.$('.gep-view-details-btn').trigger('click');assert.equal(p.$('#gep-modal-title').text(),'Sanskrit mock');p.w.document.getElementById('gep-details-modal-close').dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(p.$('#gep-details-modal')[0].style.display,'none');assert.equal(p.w.document.activeElement.className,'gep-view-details-btn');assert.deepEqual(p.errors,[]);
});
test('unused legacy translator does not break storage-restricted exams',async t=>{
 const p=await setup('<div class="gep-question-block"></div>','public/js/gep-translator.js',{GEP_Exam:{lang:'en'}},w=>Object.defineProperty(w,'sessionStorage',{get(){throw new Error('Storage denied');}}));t.after(p.close);assert.deepEqual(p.errors,[]);assert.equal(p.requests.length,0);
});
test('mirrored notifications share a pending lock and retain unread status after rejection',async t=>{
 const p=await setup('<div class="notif-item unread" data-id="1"></div><div class="gep-notification-item unread" data-id="1"></div><span class="gep-notif-count">2</span>','public/js/gep-dashboard.js');t.after(p.close);p.$('.notif-item').trigger('click');p.$('.gep-notification-item').trigger('click');assert.equal(p.requests.length,1);p.requests[0].resolve({success:true,data:{success:false}});assert.equal(p.$('.unread').length,2);assert.equal(p.$('.gep-notif-count').text(),'2');p.$('.notif-item').trigger('click');p.requests[1].resolve({success:true,data:{success:true}});assert.equal(p.$('.unread').length,0);assert.equal(p.$('.gep-notif-count').text(),'1');assert.deepEqual(p.errors,[]);
});
